### ISSUE TITLE
Pricing wrong in WordPress plugin display

### ISSUE THREAD

**Issue by chucklasker** [brownpapertickets/brown-paper-tickets-wordpress#10]
Using code paste, prices are correct:

http://kauaicommunityplayers.org/buy-tickets-to-a-kauai-community-players-live-performance/

Using the Wordpress plugin, the prices are wrong:

http://kauaicommunityplayers.org/test/

Any help?

**Comment by chantron** [comment]
Hi Chuck,

You've probably chosen to include the service fee in your prices. Go to the Plugin's settings page and then to the Event List Settings. Near the bottom under price display settings, you'll see "Include Service Fee". Enable that by selecting "Yes" and save the settings.

It should smush the service fee and ticket fee together resulting in the correct price being displayed.

**Comment by chucklasker** [comment]
I've tried it with the Include Service Fee setting on Yes and on No, but it's still the same, lower, price. This was without the cache turned off. When I enabled the cache, it shows the full price. Is that how it should behave?

**Comment by chantron** [comment]
That sounds a bit fishy, I'll take a look at this.

**Comment by chantron** [comment]
Fixed this in 8ae99207c45c78c7a2ddd279419c4c859caa2dec.
