### ISSUE TITLE
Custom date format not working

### ISSUE THREAD

**Issue by scott8872** [brownpapertickets/brown-paper-tickets-wordpress#11]
BPT Settings --> Display Settings --> Date Format

I try using the custom date format of MMMM and my date is displayed as cu0to0. Should I be using a differnt format?

Thanks.

**Comment by chantron** [comment]
Is that the entire custom date format you're using? That should work (though it would only display the full month name). I'd double check to make sure you're putting that into the date format input box and not the time format. Feel free to [email](mailto:chandler@brownpapertickets.com) me directly with your BPT username and I can take a look on our end.

You can find the full list of date format strings [here](http://momentjs.com/docs/#/displaying/format/).
