### ISSUE TITLE
Tickets sold in pairs

### ISSUE THREAD

**Issue by clickonlite** [brownpapertickets/brown-paper-tickets-wordpress#14]
We have one level of ticketing on our BPT event page that only sells in even pairs (2,4,6,8). This isn't reflected on the plugin. Does this have anything to do with editing permission for the client accounts in the developer section?

**Comment by chantron** [comment]
The API that the pulgin uses to get the pricing info doesn't show the price interval. I'll create an option that will allow you to set the interval.

**Comment by chantron** [comment]
OK, I've pushed out a new version to the Wordpress plugin repo. You should be able to upgrade shortly. To set the interval, view the page with the event list while logged in as an administrator. You'll see a new "Set interval" input box. Just enter in any number and the quantity will adjust.

**Comment by clickonlite** [comment]
I can't save the settings. Am I missing something?

**Comment by chantron** [comment]
You don't need to click save or anything. The price interval will be saved when the value has changed.
