### ISSUE TITLE
Error when trying to install + activate plugin

### ISSUE THREAD

**Issue by vckychn** [brownpapertickets/brown-paper-tickets-wordpress#24]
I'm installing the plugin through our Wordpress site using Plugins > Add New > Search for "Brown Paper Tickets" > Install Now button.

This is the error I get:
Parse error: syntax error, unexpected T_VAR, expecting ';' in /[OURSITE]/wp-content/plugins/brown-paper-tickets/src/modules/calendar/calendar-widget.php on line 181

I've installed an older version on another site without issues before.

**Comment by chantron** [comment]
What version of PHP and WordPress are you running? That line shouldn't be being parsed by PHP at all. It's part of the calendar's javascript template.

**Comment by vckychn** [comment]
Wordpress 4.2.2 and PHP 5.3.13 (the latest version my host offers)

**Comment by chantron** [comment]
Huh, two test servers I have are running 5.3.3 and have no issues with activation. Have you tried the usual deactivate other plugins troubleshooting step? 

Here's the line in question:
```php
<% for(var i = 0; i < daysOfTheWeek.length; i++ ) { %>
```

Somehow, it seems that your php install is treating the `<%` as a php shortcode.

Could you also tell me what version of the plugin you were trying to install?

**Comment by vckychn** [comment]
Yeah, I deactivated all my plugins and switched my theme to twentyfifteen. I still get that error. 

Version 0.6.3

**Comment by chantron** [comment]
I know this is old but I finally figured out what caused this. 

It seems like PHP has an ASP short tags feature which I’m guessing is enabled in your environment. It’s why PHP is reading <% as a PHP tag.

According to the PHP documentation, you can set `asp_tags` to `0` in your php.ini to disable it (It’s also been entirely removed from PHP 7).
