### ISSUE TITLE
Error when activating

### ISSUE THREAD

**Issue by atervin** [brownpapertickets/brown-paper-tickets-wordpress#7]
Parse error: syntax error, unexpected T_STRING in /home/content/08/8610908/html/wp-content/plugins/brown-paper-tickets/inc/brown-paper-tickets-plugin.php on line 6

**Comment by chantron** [comment]
Could you provide me with some more info? PHP version, Wordpress version, OS, etc?

Thanks

**Comment by chantron** [comment]
Line 6 in that file is the namespace declaration. Namespaces were introducted in PHP 5.3 so its likely you're running a version lower than that. I'm only supporting PHP 5.3 and higher.

**Comment by atervin** [comment]
Thank you.

On Wed, Feb 18, 2015 at 12:59 PM, Chandler <notifications@github.com> wrote:

> Line 6 in that file is the namespace declaration. Namespaces were
> introducted in PHP 5.3 so its likely you're running a version lower than
> that. I'm only supporting PHP 5.3 and higher.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brownpapertickets/brown-paper-tickets-wordpress/issues/7#issuecomment-74913398>
> .
>



-- 
Andrea Howard
PARENTise
http://about.me/ANDREAHOWARD/bio
http://facebook.com/parentise
