### ISSUE TITLE
BPT Events Listed Out of Order 

### ISSUE THREAD

**Issue by thomastown** [brownpapertickets/brown-paper-tickets-wordpress#8]
Hi, 

I've installed the short-code from the Brown Paper Tickets plugin but my events are showing up out of order. Is there a way to fix this bug?

Thanks,
Thomas

**Comment by chantron** [comment]
Hi Thomas,

I'm about to release an update next week and I'll add the option to sort events events chronologically based on their dates.

As it is now, the events are displayed in the order they are returned by the API (which is the order that they were created in) so there isn't anyway to re order them.

Thanks for bringing this up!

**Comment by thomastown** [comment]
Hi Chandler,

Thanks for getting back with me. I’ll pass the word on about the update.

Thanks!

**Comment by chantron** [comment]
I've added this feature and pushed the latest version of the plugin to the Wordpress plugin repository.

I've been reorganizing/restructuring the plugin and while everything seems to be OK on my dev machine and test server, I did uncover a bug when activating the plugin (which has been fixed) so let me know if you have encounter any others.
